# Generated by Django 5.2 on 2025-05-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_about_footersociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('cta_text', models.CharField(default='Explore Venues', max_length=100)),
                ('cta_url', models.URLField(default='/venues')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
